DDCA_unit-7_assignment: DDCA_unit-7_assignment.o
	gcc -o DDCA_unit-7_assignment DDCA_unit-7_assignment.o

DDCA_unit-7_assignment.o: DDCA_unit-7_assignment.s
	as -o DDCA_unit-7_assignment.o DDCA_unit-7_assignment.s

clean:
	rm *.o DDCA_unit-7_assignment
