lucernas_assignment8 LucernasAssignment8.class: lucernas_assignment8.o LucernasAssignment8.java
	gcc -o lucernas_assignment8 lucernas_assignment8.o
	javac LucernasAssignment8.java

lucernas_assignment8.o: lucernas_assignment8.s
	as -o lucernas_assignment8.o lucernas_assignment8.s

clean:
	rm *.o *.class lucernas_assignment8
