lucernas_assignment_8 LucernasAssignment8.class: lucernas_assignment_8.o LucernasAssignment8.java
	gcc -o lucernas_assignment_8 lucernas_assignment_8.o
	javac LucernasAssignment8.java

lucernas_assignment_8.o: lucernas_assignment_8.s
	as -o lucernas_assignment_8.o lucernas_assignment_8.s

clean:
	rm *.o *.class lucernas_assignment_8
